Spaceship: Blockade.o Bunk.o Controller.o Door.o Floor.o Item.o Location.o Main.o Player.o StasisCapsule.o Switch.o Terminal.o Tile.o Wall.o
	g++ Blockade.o Bunk.o Controller.o Door.o Floor.o Item.o Location.o Main.o Player.o StasisCapsule.o Switch.o Terminal.o Tile.o Wall.o -o Spaceship

Blockade.o: Blockade.cpp
	g++ -c Blockade.cpp
Bunk.o: Bunk.cpp
	g++ -c Bunk.cpp
Controller.o: Controller.cpp
	g++ -c Controller.cpp
Door.o: Door.cpp
	g++ -c Door.cpp
Floor.o: Floor.cpp
	g++ -c Floor.cpp
Item.o: Item.cpp
	g++ -c Item.cpp
Location.o: Location.cpp
	g++ -c Location.cpp
Main.o: Main.cpp
	g++ -c Main.cpp
Player.o: Player.cpp
	g++ -c Player.cpp
StasisCapsule.o: StasisCapsule.cpp
	g++ -c StasisCapsule.cpp
Switch.o: Switch.cpp
	g++ -c Switch.cpp
Terminal.o: Terminal.cpp
	g++ -c Terminal.cpp
Tile.o: Tile.cpp
	g++ -c Tile.cpp
Wall.o: Wall.cpp
	g++ -c Wall.cpp

clean:
	rm -f Spaceship *.o